name: fluttre_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_slidable: ^3.1.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/Images/OIG1.jpeg
    - lib/Images/fsfc.png
